// <auto-generated />
using System;
using FinanceAnalysis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceAnalysis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260725005518_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceAnalysis.Domain.Catalog.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cik")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("cik");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("integer")
                        .HasColumnName("employee_count");

                    b.Property<string>("HomepageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("homepage_url");

                    b.Property<int?>("IndustryId")
                        .HasColumnType("integer")
                        .HasColumnName("industry_id");

                    b.Property<DateOnly?>("ListedOn")
                        .HasColumnType("date")
                        .HasColumnName("listed_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("ProfileRefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("profile_refreshed_at");

                    b.Property<int?>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("IndustryId")
                        .HasDatabaseName("ix_companies_industry_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_companies_name");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("ix_companies_sector_id");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Catalog.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.HasKey("Id")
                        .HasName("pk_industries");

                    b.HasIndex("SectorId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_industries_sector_id_name");

                    b.ToTable("industries", (string)null);
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Catalog.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sectors");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_sectors_key");

                    b.ToTable("sectors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Key = "Energy",
                            Name = "Energy"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Key = "Materials",
                            Name = "Materials"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Key = "Industrials",
                            Name = "Industrials"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Key = "ConsumerDiscretionary",
                            Name = "Consumer Discretionary"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Key = "ConsumerStaples",
                            Name = "Consumer Staples"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Key = "HealthCare",
                            Name = "Health Care"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Key = "Financials",
                            Name = "Financials"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Key = "InformationTechnology",
                            Name = "Information Technology"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Key = "CommunicationServices",
                            Name = "Communication Services"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Key = "Utilities",
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Key = "RealEstate",
                            Name = "Real Estate"
                        });
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Catalog.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("asset_type");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<DateOnly?>("DelistedOn")
                        .HasColumnType("date")
                        .HasColumnName("delisted_on");

                    b.Property<string>("Exchange")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("exchange");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tracked");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("symbol");

                    b.Property<DateTimeOffset?>("TrackedSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tracked_since");

                    b.Property<DateTimeOffset?>("UntrackedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("untracked_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stocks");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_stocks_company_id");

                    b.HasIndex("IsTracked")
                        .HasDatabaseName("ix_stocks_is_tracked")
                        .HasFilter("is_tracked");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_stocks_symbol");

                    b.ToTable("stocks", (string)null);
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Identity.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_external_logins_user_id");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("ix_external_logins_provider_provider_key");

                    b.ToTable("external_logins", (string)null);
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_id_expires_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_normalized_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full access, including internal ingestion endpoints and universe management.",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Standard access to market data, portfolios and recommendations.",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.MarketData.DailyPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("close");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("high");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("open");

                    b.Property<int>("StockId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_id");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date")
                        .HasColumnName("trade_date");

                    b.Property<int?>("TransactionCount")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_count");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.Property<decimal?>("VolumeWeightedAveragePrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("volume_weighted_average_price");

                    b.HasKey("Id")
                        .HasName("pk_daily_prices");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_daily_prices_data_source_id");

                    b.HasIndex("TradeDate")
                        .HasDatabaseName("ix_daily_prices_trade_date_brin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TradeDate"), "brin");

                    b.HasIndex("StockId", "TradeDate")
                        .IsUnique()
                        .HasDatabaseName("ux_daily_prices_stock_trade_date");

                    b.ToTable("daily_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_daily_prices_high_low", "high >= low");

                            t.HasCheckConstraint("ck_daily_prices_positive", "open > 0 AND high > 0 AND low > 0 AND close > 0");

                            t.HasCheckConstraint("ck_daily_prices_volume", "volume >= 0");
                        });
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.MarketData.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_data_sources");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_data_sources_key");

                    b.ToTable("data_sources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "polygon",
                            Name = "Polygon.io"
                        },
                        new
                        {
                            Id = 2,
                            Key = "mock",
                            Name = "Deterministic Mock Provider"
                        });
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.MarketData.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("data_source_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<DateOnly?>("RangeEnd")
                        .HasColumnType("date")
                        .HasColumnName("range_end");

                    b.Property<DateOnly?>("RangeStart")
                        .HasColumnType("date")
                        .HasColumnName("range_start");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("integer")
                        .HasColumnName("records_inserted");

                    b.Property<int>("RecordsSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("records_skipped");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("run_type");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("SymbolsReceived")
                        .HasColumnType("integer")
                        .HasColumnName("symbols_received");

                    b.Property<int>("SymbolsRequested")
                        .HasColumnType("integer")
                        .HasColumnName("symbols_requested");

                    b.Property<DateOnly?>("TradeDate")
                        .HasColumnType("date")
                        .HasColumnName("trade_date");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_runs");

                    b.HasIndex("DataSourceId")
                        .HasDatabaseName("ix_ingestion_runs_data_source_id");

                    b.HasIndex("QueuedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_ingestion_runs_queued_at");

                    b.HasIndex("RunType", "TradeDate", "Status")
                        .HasDatabaseName("ix_ingestion_runs_run_type_trade_date_status");

                    b.ToTable("ingestion_runs", (string)null);
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Portfolios.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_portfolios");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_portfolios_user_id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_portfolios_user_id_name");

                    b.ToTable("portfolios", (string)null);
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Portfolios.PortfolioHolding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("average_cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("OpenedOn")
                        .HasColumnType("date")
                        .HasColumnName("opened_on");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<int>("StockId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_holdings");

                    b.HasIndex("StockId")
                        .HasDatabaseName("ix_portfolio_holdings_stock_id");

                    b.HasIndex("PortfolioId", "StockId")
                        .IsUnique()
                        .HasDatabaseName("ix_portfolio_holdings_portfolio_id_stock_id");

                    b.ToTable("portfolio_holdings", null, t =>
                        {
                            t.HasCheckConstraint("ck_portfolio_holdings_average_cost", "average_cost >= 0");

                            t.HasCheckConstraint("ck_portfolio_holdings_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Predictions.MlModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_ml_models");

                    b.HasIndex("Key", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_ml_models_key_version");

                    b.ToTable("ml_models", (string)null);
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Predictions.MlPrediction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(9, 8)
                        .HasColumnType("numeric(9,8)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("integer")
                        .HasColumnName("horizon_days");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<decimal?>("PredictedClose")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("predicted_close");

                    b.Property<decimal?>("PredictedReturn")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("predicted_return");

                    b.Property<DateOnly>("PredictionDate")
                        .HasColumnType("date")
                        .HasColumnName("prediction_date");

                    b.Property<string>("Signal")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("signal");

                    b.Property<int>("StockId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_id");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.HasKey("Id")
                        .HasName("pk_ml_predictions");

                    b.HasIndex("StockId", "PredictionDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ml_predictions_stock_id_prediction_date");

                    b.HasIndex("ModelId", "StockId", "PredictionDate", "TargetDate")
                        .IsUnique()
                        .HasDatabaseName("ux_ml_predictions_model_stock_dates");

                    b.ToTable("ml_predictions", null, t =>
                        {
                            t.HasCheckConstraint("ck_ml_predictions_confidence", "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)");
                        });
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Predictions.MlPredictionHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AbsoluteError")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("absolute_error");

                    b.Property<decimal?>("ActualValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("actual_value");

                    b.Property<bool?>("DirectionCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("direction_correct");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer")
                        .HasColumnName("model_id");

                    b.Property<decimal?>("PercentageError")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("percentage_error");

                    b.Property<decimal?>("PredictedValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("predicted_value");

                    b.Property<long>("PredictionId")
                        .HasColumnType("bigint")
                        .HasColumnName("prediction_id");

                    b.Property<int>("StockId")
                        .HasColumnType("integer")
                        .HasColumnName("stock_id");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.HasKey("Id")
                        .HasName("pk_ml_prediction_history");

                    b.HasIndex("PredictionId")
                        .IsUnique()
                        .HasDatabaseName("ix_ml_prediction_history_prediction_id");

                    b.HasIndex("StockId")
                        .HasDatabaseName("ix_ml_prediction_history_stock_id");

                    b.HasIndex("ModelId", "TargetDate")
                        .HasDatabaseName("ix_ml_prediction_history_model_id_target_date");

                    b.ToTable("ml_prediction_history", (string)null);
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Catalog.Company", b =>
                {
                    b.HasOne("FinanceAnalysis.Domain.Catalog.Industry", "Industry")
                        .WithMany("Companies")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_companies_industries_industry_id");

                    b.HasOne("FinanceAnalysis.Domain.Catalog.Sector", "Sector")
                        .WithMany("Companies")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_companies_sectors_sector_id");

                    b.Navigation("Industry");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Catalog.Industry", b =>
                {
                    b.HasOne("FinanceAnalysis.Domain.Catalog.Sector", "Sector")
                        .WithMany("Industries")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_industries_sectors_sector_id");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Catalog.Stock", b =>
                {
                    b.HasOne("FinanceAnalysis.Domain.Catalog.Company", "Company")
                        .WithMany("Stocks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stocks_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Identity.ExternalLogin", b =>
                {
                    b.HasOne("FinanceAnalysis.Domain.Identity.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_logins_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("FinanceAnalysis.Domain.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("FinanceAnalysis.Domain.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("FinanceAnalysis.Domain.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.MarketData.DailyPrice", b =>
                {
                    b.HasOne("FinanceAnalysis.Domain.MarketData.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_prices_data_sources_data_source_id");

                    b.HasOne("FinanceAnalysis.Domain.Catalog.Stock", "Stock")
                        .WithMany("DailyPrices")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_daily_prices_stocks_stock_id");

                    b.Navigation("DataSource");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.MarketData.IngestionRun", b =>
                {
                    b.HasOne("FinanceAnalysis.Domain.MarketData.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_runs_data_sources_data_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Portfolios.Portfolio", b =>
                {
                    b.HasOne("FinanceAnalysis.Domain.Identity.User", "User")
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolios_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Portfolios.PortfolioHolding", b =>
                {
                    b.HasOne("FinanceAnalysis.Domain.Portfolios.Portfolio", "Portfolio")
                        .WithMany("Holdings")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_holdings_portfolios_portfolio_id");

                    b.HasOne("FinanceAnalysis.Domain.Catalog.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_holdings_stocks_stock_id");

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Predictions.MlPrediction", b =>
                {
                    b.HasOne("FinanceAnalysis.Domain.Predictions.MlModel", "Model")
                        .WithMany("Predictions")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ml_predictions_ml_models_model_id");

                    b.HasOne("FinanceAnalysis.Domain.Catalog.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ml_predictions_stocks_stock_id");

                    b.Navigation("Model");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Predictions.MlPredictionHistory", b =>
                {
                    b.HasOne("FinanceAnalysis.Domain.Predictions.MlModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ml_prediction_history_ml_models_model_id");

                    b.HasOne("FinanceAnalysis.Domain.Predictions.MlPrediction", "Prediction")
                        .WithMany("History")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ml_prediction_history_ml_predictions_prediction_id");

                    b.HasOne("FinanceAnalysis.Domain.Catalog.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ml_prediction_history_stocks_stock_id");

                    b.Navigation("Model");

                    b.Navigation("Prediction");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Catalog.Company", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Catalog.Industry", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Catalog.Sector", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Industries");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Catalog.Stock", b =>
                {
                    b.Navigation("DailyPrices");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Identity.User", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("Portfolios");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Portfolios.Portfolio", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Predictions.MlModel", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("FinanceAnalysis.Domain.Predictions.MlPrediction", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
